vim.opt.clipboard = 'unnamedplus'
vim.opt.undofile = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.updatetime = 250
vim.opt.completeopt = 'menu,menuone,noselect'
vim.opt.termguicolors = true
vim.opt.signcolumn = 'yes'
vim.opt.copyindent = true
vim.opt.expandtab = true
vim.opt.autoindent = true
vim.opt.cursorline = true
vim.opt.hlsearch = true
vim.opt.list = true
vim.opt.number = true
vim.opt.numberwidth=4
vim.opt.relativenumber = true
vim.opt.preserveindent = true
vim.opt.quoteescape = "\\"
vim.opt.shiftwidth = 4
vim.opt.showcmd = false
vim.opt.wrap = false
vim.opt.showbreak = "|=> "
vim.opt.smartindent = true
vim.opt.smarttab = true
vim.opt.smoothscroll = true
vim.opt.softtabstop = 4
vim.opt.virtualedit = all
